#Complementing a Strand of DNA 

def complementary(s):
    #Given a string DNA sequence s 
    #Returns reverse complement of the strand 

    complement = ""
    
    #Creates complementary strand: 
    for nucleotide in s:
        if nucleotide == 'A':
            complement = complement + 'T'
        elif nucleotide == 'T':
            complement = complement + 'A'
        elif nucleotide == 'C':
            complement = complement + 'G'
        elif nucleotide == 'G':
            complement = complement + 'C'
        else:
            print("Error in nucleotide sequence")
            
    #Reverse DNA string 
    reverse_complement = complement[::-1]

    print(reverse_complement)

s = 'AAAACCCGGT'
complementary(s)

s1 = 'ATGCTACAGCTCGCAAGCACTAAATTCTTGCTCAGTAGATACTCCCCTAGAGCCAGGCTACCTAAACGAGCTGATTCATCCTCCGAAATTCCTGCGGAATGCAGAGGAACCTCTCTTGTAGCATTCAACCGTACCGAGTGATATGGGCGCTTCTCGAACGACCTACGGATTTACCACCACTAAGTGGGAGCGATGGAGTGTTTACAGTTCCTCTGCTGGAGTTTAGTCATCTATGGGACTAAAATCTGACCAACCGGTTGCGGGAACCGCTTAGTTCGCGTACAGCCCCTCATGCTAGTGGTTAGCGTCTAGCACGATTGTGGGAGGAGTGAGGCTAACTATCGACAGACTGAACACTTGAACGTACCTCCAGTGAATGAGGGCGACTAGAGAGCCGCCATGTAAGTGACGAGCCAACAAGTCCAGAACCTATGGCGTTCAATCAACAGTCTTAAACGAAGTGTAAGGAATGGCTAATAAGCATAAGCATGAAATAGGGAAATAGGGGGCTACTAGTTGGCCCGCTGCGACTAGCAGCGACCTGGCAACTTCGACGCTTAAAAATCTTGGGAGCATGAAATTCGCCAATATCAAGCGTTATCCGTAACATACGTCGTGTGTATGTATCATTTTCACTGCCAGGCGCCTACTTCCGTTGAGATAAGAGCTTCATATAGTAGGTGAGAAACGCAAAGAGCAGAGATGGGCTGTCATCTACTTCAATTCGACCCTTCAGCTCAACGTGCCGCGAATAATAATCGTTTGTGTAGACGTTGGTCCAGGAGACGTATTCCCCGAAGATGCAATACGTTAGTTGCATGGGTCAAATCACCCCGGCTGTCTTAATAGATGCTGATCATGTGGCCGGGACTTCACGAATTGGTCAATGGGTGAGCAACTACTAGGATACAATTCTGGAGTCTATGGACCAAAATAGTATATTCT'
complementary(s1)
