# Purpose is to transcribe DNA to RNA 

def transcribe(t):
    #Given a DNA string t of at most 1000 nt
    # Returns transcribed DNA to RNA sequence 
    RNA = ""
    for nucleotide in t:
        if nucleotide == "T":
            RNA = RNA + "U"
        else:
            RNA = RNA + nucleotide
    
    print(RNA)

DNA = 'GATGGAACTTGACTACGTAAATT'

transcribe(DNA)

DNA1 = 'TCACTTTAATCTGGCTAATGATTACAACGGCGTTCGATAAACCTGTTGTAGTACACCAGGTGTCGCAGGTTATGATGTGCGAAGACTCAATCTTGTGTATGCTATAAACTCTCTATTGTACTGCCTCTTAGTACCACCAGGTCAGTTGGTCCCATCCTTGATACTAATTAAGTTTTACAATACTGGTGTCAAAGCTGGGGCTAGAGAGATTGCGGAGACCTGAAAAAATTCTCCGAACTAAACGCCGCAGTTAGACCATTCCGAATCGTCCGCCCCTCGTGGTGTCCAAGGTCGTTGGTGCCGTGCTTGAAGGAGGTTCATCCACGTAGGATTGTGAGAATGCGCTTCTGGGTCGCCGTACATTACTGGTCTGTTGACGTCTAGATGCATTCAAGGGGGGGACAGAACTAGGTAGTTCGAGGGGGGCCCGTCTCCAATTCGGCCGCATCGAAAAGATACTTATAACCTTCTAGCATCCATCCGAGCCCATCCTCGCTAGCATGTAGTGTCATATTTCCAGACGAGCGAGTCACAACTGATTCGCCCACCTACCAAAGTGTCCAGGGATAAACGCCTTATAGTAGCCCCCTGGCGCACGGTTCCTGGAGCACAGGCAGCCTCCCCGATGGATTGTTTTCGCGATACGACACCAATTTACTCGGGGGCTAGGACAAACCCACACGGGATCGTATTTGGGGGGTTGTGAGGTAACCGCCAGCGGATCAGAGCGTATCATTTTACACGGCCCCATGCGGTAGAGATCGAGCACGCCGGCTGCACTACTCCTAAAATCATGATTCGACGGGGGACGCTACGGAACTGAGGTTTGCACACTTAGCTTACAGGATGCTATGTGGATAGGAGCGAAAGCAAGCTTGGGCCTGTACGAATCTGTGAAGCTAGTGCCAATTCACTATAACGGCGCGTAGAGCAGACGGTGAGGGGCGTTTGTCTAAAGAAACCTCAAATACAAGTC'

transcribe(DNA1)